monolog:
    handlers:
        kafka_handler:
            type:  service
            id: kafka_handler
            level: debug
        main:
            type:  service
            id: kafka_handler
            level: debug
        nested:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug
        console:
            type:   console
            process_psr_3_messages: false
            channels: ["!event", "!doctrine"]
        grouped:
            type:               group
            members:            [nested, kafka_handler]